image: node:latest

cache:
  paths:
  - node_modules/

stages:
  - test
  - deploy

develop-test:
  stage: test
  script:
  - yarn install
  - yarn build
  artifacts:
    paths:
    - public
  environment:
    name: development
    url: https://rdricco.gitlab.io/Iandi-Gatsby-Starter

  except:
  - master
  - develop


pages:
  stage: deploy
  script:
  - yarn install
  - yarn build
  artifacts:
    paths:
    - public
  environment:
    name: production
    url: https://rdricco.gitlab.io/Iandi-Gatsby-Starter

  only:
  - master
  - develop
