language: node

cache:
  yarn: true
  directories:
    - "node_modules"

before_script:
  - yarn install

script:
  - yarn build

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  verbose: true
  skip-cleanup: true
  keep-history: true
  local-dir: public
  on:
    branch: master