language: node

cache:
  yarn: true
  directories:
    - "node_modules"

install:
 - yarn install

script: yarn build
    "build:gh": "npm run clean && npm run build:pp && gh-pages -d public"


deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  verbose: true
  skip-cleanup: true
  keep-history: true
  local-dir: public
  on:
    branch: master